account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='login.html'
        ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('mypage/', views.my_page, name='mypage'),
    path('signup/', views.signup, name='signup'),
]

comento_main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
    path('products/', include('products.urls')),
    path('account/', include('account.urls')),  # TODO: 추후에 프로젝트에 맞게 수정해야 함
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/urls.py
from django.urls import path
from . import views


app_name = 'company'

urlpatterns = [
    path('', views.intro),
    path('intro/', views.intro, name='intro'),
    path('organization/', views.organization, name='organization'),
    path('history/', views.history, name='history'),
    path('link/', views.link, name='link'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls')),
    path('products/', include('products.urls')),
]

products/urls.py
from django.urls import path
from . import views


app_name = 'products'

urlpatterns = [
    path('lists', views.ProductList.as_view(), name='lists'),
    path('<int:product_id>/<str:menu>', views.detail, name='detail')
]

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

company/models.py
from django.db import models

# Create your models here.

products/models.py
import os
from uuid import uuid4
from django.utils.deconstruct import deconstructible
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User


@deconstructible
class PathAndRename(object):
    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # UUID를 사용하여 파일 이름 생성
        filename = f'{uuid4().hex}.{ext}'
        # 기존 경로 구조 유지
        return os.path.join(self.path, filename)


# 회사 상품
class Product(models.Model):
    name = models.CharField(max_length=30)  # 이름
    pub_date = models.DateField('date published')  # 출시일
    price = models.IntegerField(validators=[MinValueValidator(0)])  # 상품 가격(원)
    desc = models.TextField()  # 상품 상세 설명
    summary = models.CharField(max_length=50)  # 상품 요약 설명
    img = models.ImageField(
        upload_to=PathAndRename('products/images/%Y/%M/%d/'),
        null=True,
        blank=True
    )  # 상품 이미지 경로

    def __str__(self):
        return f'[{self.pk}]{self.name}'


# 상품 리뷰
class Review(models.Model):
    title = models.CharField(max_length=50)  # 리뷰 제목
    review = models.TextField()  # 리뷰글
    score = models.SmallIntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(10)])  # 평점(0~10, 정수)
    pub_date = models.DateTimeField(auto_now_add=True)  # 게시일
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 작성자(id)
    create_date = models.DateTimeField(auto_now_add=True)  # 작성 시간
    modify_date = models.DateTimeField(auto_now=True)  # 수정 시간

    def __str__(self):
        return f'[{self.pk}]{self.title}'

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput, max_length=100)


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=100)

    class Meta:
        model = User
        fields = (
            "username",
            "password1",
            "password2",
            "email"
        )

    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) < 6:
            raise ValidationError("idLengthError")
        return username

    def clean_password1(self):
        password = self.cleaned_data['password1']
        if len(password) < 8:
            raise ValidationError("pwLengthError")
        return password

account/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import SignupForm


def my_page(request):
    return render(request, 'mypage.html')


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})

company/views.py
from django.shortcuts import render


def company_view(request, state):
    context = {
        'state': state
    }
    return render(request, 'company.html', context)


def intro(request):
    return company_view(request, 'intro')


def organization(request):
    return company_view(request, 'organization')


def history(request):
    return company_view(request, 'history')


def link(request):
    return company_view(request, 'link')

products/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from .models import Product


class ProductList(ListView):
    model = Product
    template_name = 'products.html'
    context_object_name = 'products_list'
    paginate_by = 30
    ordering = ['-pub_date', '-price']


def detail(request, product_id, menu):
    product_list = get_object_or_404(Product, pk=product_id)
    context = {'product_list': product_list, 'menu': menu}
    return render(request, 'product_detail.html', context)

templates/company.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>메인 페이지</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .tab_btn {
            border: transparent;
            color: rgba(0, 0, 0, 0.65);
        }
    </style>
</head>
<body>
<!-- 상단 헤더 -->
{% include "top_nav.html" with isCompany=True %}

<!-- 하단 헤더 -->
<nav class="navbar navbar-expand-lg shadow-sm" style="background-color: rgba(10,8,120,0.15);">
    <div class="container-fluid" style="width: 90%">
        <div class="col text-center">
            <a type="button" class="btn btn-outline-success tab_btn {% if state == 'intro' %}active{% endif %}" href="{% url 'company:intro' %}">소개</a>
        </div>
        <div class="col text-center">
            <a type="button" class="btn btn-outline-success tab_btn {% if state == 'organization' %}active{% endif %}" href="{% url 'company:organization' %}">조직도</a>
        </div>
        <div class="col text-center">
            <a type="button" class="btn btn-outline-success tab_btn {% if state == 'history' %}active{% endif %}" href="{% url 'company:history' %}">연표</a>
        </div>
        <div class="col text-center">
            <a type="button" class="btn btn-outline-success tab_btn {% if state == 'link' %}active{% endif %}" href="{% url 'company:link' %}">링크</a>
        </div>
    </div>
</nav>

<!-- 내용 포함 -->
{% include "company/"|add:state|add:".html" %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/company/history.html
<div class="container">
    <br>
    <div class="row gap-2">
        <div class="col-4 border rounded p-3">
            {% load static %}
            <img src="{% static 'images/history.webp' %}" alt="이미지 없음!" class="img-fluid">
        </div>
        <div class="col border rounded p-3 bg-body-tertiary">
            {% lorem 2 p %}
        </div>
        <div class="col-12 border rounded p-3 bg-body-tertiary">
            {% lorem 3 p %}
        </div>
    </div>
</div>

templates/company/intro.html
<div class="container">
    <br>
    <div class="row g-2">
        <div class="col-4">
            <div class="border rounded bg-body-tertiary">
                {% load static %}
                <img src="{% static 'images/company.svg' %}" alt="이미지 없음!" class="img-fluid">
            </div>
        </div>
        <div class="col-8">
            <div class="container-fluid">
                <div class="row gy-2">
                    <div class="col-12 border rounded bg-body-tertiary p-2">
                        {% lorem 1 p %}
                    </div>
                    <div class="col-12 border rounded bg-body-tertiary p-2">
                        {% lorem 1 p %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="border rounded bg-body-tertiary p-2">
                {% lorem 3 p %}
            </div>
        </div>
    </div>
</div>

templates/company/link.html
<div class="container">
    <br>
    <div class="row g-2 text-center">
        {# TODO: 링크 추가 #}
        <div class="col-6">
            <div class="border rounded p-3 bg-body-secondary">
                링크
            </div>
        </div>
        <div class="col-6">
            <div class="border rounded p-3 bg-success-subtle">
                링크
            </div>
        </div>
        <div class="col-6">
            <div class="border rounded p-3 bg-warning-subtle">
                링크
            </div>
        </div>
        <div class="col-6">
            <div class="border rounded p-3 bg-dark-subtle">
                링크
            </div>
        </div>
    </div>
</div>

templates/company/organization.html
<div class="container">
    <br>
    <div class="row gap-2">
        <div class="col-4 border rounded p-3">
            {% load static %}
            <img src="{% static 'images/org.png' %}" alt="이미지 없음!" class="img-fluid">
        </div>
        <div class="col border rounded p-3 bg-body-tertiary">
            {% lorem 2 p %}
        </div>
        <div class="col-12 border rounded p-3 bg-body-tertiary">
            {% lorem 3 p %}
        </div>
    </div>
</div>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>로그인</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .form-div {
            display: grid;
            place-items: center;
            height: 40vh;
        }
        #auth_btn {
            width: 100%;
        }
        #nav_button {
            border: transparent;
            border-radius: 25pt;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg shadow-sm" style="background-color: aquamarine">
    <div class="d-flex justify-content-between container-fluid" style="height: 64px; width: 80%">
        <div>
            <button id="nav_button" onclick="history.back()" class="btn btn-outline-secondary">
                뒤로가기
            </button>
        </div>
        <div>
            <span class="fs-3">로그인/회원가입</span>
        </div>
        <div>
            <a id="nav_button" class="btn btn-outline-secondary" href="{% url 'company:intro' %}">
                Home
            </a>
        </div>
    </div>
</nav>

<div id="content" class="container">
    <div class="form-div">
        {% if next %}
            {% if user.is_authenticated %}
                <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
            {% else %}
                <p>Please login to see this page.</p>
            {% endif %}
        {% endif %}
        <form method="post" action="{% url 'account:login' %}">
        {% csrf_token %}
            <div class="mb-2">
                <input type="text" class="form-control form-control-lg" id="InputID"
                       aria-describedby="emailHelp" placeholder="ID" name="username" required>
            </div>
            <div class="mb-2">
                <input type="password" class="form-control form-control-lg"
                       id="InputPassword" placeholder="비밀번호" name="password" required>
            </div>
            <div class="mb-2">
                <div class="row gx-2">
                    <div class="col">
                        <button type="submit" id="auth_btn" class="btn btn-primary btn-lg">로그인</button>
                    </div>
                    <div class="col">
                        <a id="auth_btn" class="btn btn-secondary btn-lg"
                                href="{% url 'account:signup' %}">회원가입</a>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-sm btn-outline-success"
                    style="border: transparent">ID/비밀번호 찾기</button>
            <input type="hidden" name="next" value="{{ next }}">
        </form>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/mypage.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>마이페이지</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        #nav_button {
            border: transparent;
            border-radius: 25pt;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg shadow-sm" style="background-color: aquamarine">
    <div class="d-flex justify-content-between container-fluid" style="height: 64px; width: 80%">
        <div>
            <button id="nav_button" onclick="history.back()" class="btn btn-outline-secondary">
                뒤로가기
            </button>
        </div>
        <div>
            <span class="fs-3">마이페이지</span>
        </div>
        <div>
            <a id="nav_button" class="btn btn-outline-secondary" href="{% url 'company:intro' %}">
                Home
            </a>
        </div>
    </div>
</nav>
{# TODO: body 부분 채우기 #}
<form action="{% url 'account:logout' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="로그아웃" />
</form>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/product_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>상세페이지</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<!-- 상단 헤더 -->
{% include "top_nav.html" with isCompany=False %}

<br>
<div class="container">
    <div class="row g-2">
        <div class="col-12">
            <div class="row gx-2">
                <div class="col-4">
                    <div class="border rounded p-2">
                        {% if product_list.img %}
                            <img class="img-fluid" src="{{ product_list.img.url }}" alt="{{ product_list.name }}">
                        {% else %}
                            {% load static %}
                            <img class="img-fluid" src="{% static 'images/img_placeholder.svg' %}" alt="Default Image">
                        {% endif %}
                    </div>
                </div>
                <div class="col-8">
                    <div class="border rounded p-2" style="height: 100%">
                        <p class="text-body-tertiary">
                            {{ product_list.summary }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="border-bottom border-dark-subtle" style="width: fit-content">
                <a href="{% url 'products:detail' product_id=product_list.id menu='price' %}"
                   class="m-3 fs-5 link-opacity-50 link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover {% if menu == 'price' %}link-opacity-75 link-underline-opacity-75{% endif %}">가격</a>
                <a href="{% url 'products:detail' product_id=product_list.id menu='desc' %}"
                   class="m-3 fs-5 link-opacity-50 link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover {% if menu == 'desc' %}link-opacity-75 link-underline-opacity-75{% endif %}">상세</a>
                <a href="{% url 'products:detail' product_id=product_list.id menu='review' %}"
                   class="m-3 fs-5 link-opacity-50 link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover {% if menu == 'review' %}link-opacity-75 link-underline-opacity-75{% endif %}">리뷰</a>
                <a href="{% url 'products:detail' product_id=product_list.id menu='purchase' %}"
                   class="m-3 fs-5 link-opacity-50 link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover {% if menu == 'purchase' %}link-opacity-75 link-underline-opacity-75{% endif %}">구매</a>
            </div>
        </div>
    </div>
</div>

<!-- 내용 포함 -->
{% include "product_detail/"|add:menu|add:".html" %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/product_detail/desc.html
<br>
<div class="container">
    <div class="border rounded p-2">
        제품 상세 설명
    </div>
</div>

templates/product_detail/price.html
<div class="container">
    price
</div>

templates/product_detail/purchase.html
<div class="container">
    purchase
</div>

templates/product_detail/review.html
<div class="container">
    review
</div>

templates/products.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>제품</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .square_img {
            aspect-ratio: 1/1;
            object-fit: contain;
        }
    </style>
</head>
<body>
<!-- 상단 헤더 -->
{% include "top_nav.html" with isCompany=False %}

<div class="container">
    <br>
    <div class="row row-cols-5 g-2">
        {% for product in products_list %}
            <div class="col">
            <div class="card">
                <a href="{% url 'products:detail' product_id=product.id menu='price' %}">
                    {% if product.img %}
                        <img class="card-img-top square_img" src="{{ product.img.url }}" alt="{{ product.name }}">
                    {% else %}
                        {% load static %}
                        <img class="card-img-top square_img" src="{% static 'images/img_placeholder.svg' %}" alt="Default Image">
                    {% endif %}
                </a>
                <div class="card-body border-top">
                    <h5 class="card-title fw-bold">{{ product.name }}</h5>
                    <h6 class="card-subtitle text-secondary-emphasis" style="margin-bottom: 10px">{{ product.price|stringformat:"s"|add:"\\" }}</h6>
                    <p class="card-text text-body-tertiary">
                        {{ product.summary }}
                    </p>
                </div>
            </div>
            </div>
        {% endfor %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>회원가입</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        #nav_button {
            border: transparent;
            border-radius: 25pt;
        }
        #form-div {
            place-items: center;
            width: 400px;
        }
        #auth_btn {
            width: 100%;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg shadow-sm" style="background-color: rgba(251,33,33,0.38)">
    <div class="d-flex justify-content-between container-fluid" style="height: 64px; width: 80%">
        <div>
            <button id="nav_button" onclick="history.back()" class="btn btn-outline-secondary">
                뒤로가기
            </button>
        </div>
        <div>
            <span class="fs-3">회원가입</span>
        </div>
        <div>
            <a id="nav_button" class="btn btn-outline-secondary" href="{% url 'company:intro' %}">
                Home
            </a>
        </div>
    </div>
</nav>

<br>

<div class="container" id="form-div">
<form method="post" action="{% url 'account:signup' %}">
    {% csrf_token %}
    <div class="mb-3">
        <input type="text" class="form-control form-control-lg" name="username" id="username"
               value="{{ form.username.value|default_if_none:'' }}" placeholder="ID" required>
        <div id="idHelp" class="form-text">영어, 숫자 및 특수문자만 가능, 최소 6글자</div>
    </div>
    <div class="mb-3">
        <input type="password" class="form-control form-control-lg" name="password1" id="password1"
               value="{{ form.password1.value|default_if_none:'' }}" placeholder="비밀번호" required>
        <div id="pwHelp" class="form-text">영어, 숫자 및 특수문자만 가능, 최소 8글자</div>
    </div>
    <div class="mb-3">
        <input type="password" class="form-control form-control-lg" name="password2" id="password2"
               value="{{ form.password2.value|default_if_none:'' }}" placeholder="비밀번호 확인" required>
        <div id="pw2Help" class="form-text">입력한 비밀번호를 다시 한번 입력해주세요</div>
    </div>
    <div class="mb-3">
        <input type="text" class="form-control form-control-lg" name="email" id="email"
               value="{{ form.email.value|default_if_none:'' }}" placeholder="이메일 주소" required>
        <div id="emailHelp" class="form-text">비밀번호 재설정을 위한 이메일 주소를 입력해주세요</div>
    </div>
    <div class="mb-3">
        <div class="row gx-2">
            <div class="col">
                <button type="submit" id="auth_btn" class="btn btn-primary btn-lg">회원가입</button>
            </div>
            <div class="col">
                <a id="auth_btn" class="btn btn-secondary btn-lg" href="#">중복확인</a>
            </div>
        </div>
    </div>
</form>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/top_nav.html
<!-- 회사 페이지와 제품 페이지 모두에 포함되는 최상단 탭 -->
<nav class="navbar navbar-expand-lg shadow-sm" style="background-color: rgba(29,22,232,0.15);">
    <div class="container-fluid" style="height: 64px; width: 90%">
        <div class="col text-start">
            <a type="button" class="btn btn-outline-secondary {{ isCompany|yesno:'active,' }}"
               style="border: transparent; border-radius: 25pt;" href="{% url 'company:intro' %}">회사</a>
            <a type="button" class="btn btn-outline-secondary {{ isCompany|yesno:',active' }}"
               style="border: transparent; border-radius: 25pt;" href="{% url 'products:lists' %}">제품</a>
        </div>
        <div class="col text-center">
            <a class="navbar-brand fs-3" href="{% url 'company:intro' %}">Home</a>
        </div>
        <div class="col text-end">
            {% if user.is_authenticated %}
                <a type="button" class="btn btn-sm btn-outline-secondary"
                   style="border-radius: 25pt;" href="{% url 'account:mypage' %}">마이페이지</a>
            {% else %}
                <a type="button" class="btn btn-sm btn-outline-secondary"
                   style="border-radius: 25pt;" href="{% url 'account:login' %}">로그인/회원가입</a>
            {% endif %}
        </div>
    </div>
</nav>